version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: skypia-postgres
    environment:
        POSTGRES_DB: skypia
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 393406
    ports:
      - "5436:5432"
    volumes:
      - db:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    container_name: skypia-mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3307:3306"
    volumes:
      - my-db:/var/lib/mysql

  skypia:
    build:
        dockerfile: Dockerfile
        context: skypia
    container_name: skypia
    ports:
      - 8080:8080
    volumes: 
      - ./skypia:/app 
    depends_on:
      - postgres
      - mysql

  auth:
    build: 
      context: auth
      dockerfile: Dockerfile
    container_name: skypia-auth
    ports: 
      - 8081:8080
    volumes: 
      - ./auth:/app 
    depends_on:
      - postgres

volumes:
  auth:
  skypia:
  db:
  my-db: